---
# Determines if the installation is shared/system-wide or user-specific.
neovim_shared: false
neovim_bin_shared: true

# Define the user for whom Neovim will be installed.
neovim_user: "{{ dotfiles_user_id }}"
neovim_bin_user: "{{ 'root' if neovim_bin_shared else neovim_user }}"

# Define the group for which Neovim will be installed.
neovim_user_group: "{{ neovim_user }}"


neovim_install_dir: "~{{ neovim_user }}/neovim"

neovim_bin_dir: >-
  {{ '/usr/local' if neovim_bin_shared
     else '~' + neovim_user + '/.local' }}


# Git repo to clone for building Neovim from source.
neovim_repo: "https://github.com/neovim/neovim.git"
# Branch to build from (default: master).
neovim_version: "master"

neovim_dotfiles_dir: "~{{ neovim_user }}/.dotfiles"
neovim_src_config_dir: "{{ neovim_dotfiles_dir }}/nvim"
neovim_dest_config_dir: "~{{ neovim_user }}/.config/nvim"

neovim_enable_github_copilot: true
neovim_github_copilot_src_dir: "{{ neovim_dotfiles_dir }}/github-copilot"
neovim_github_copilot_src_key: "{{ neovim_github_copilot_src_dir }}/apps.json"
neovim_github_copilot_dest_dir: "~{{ neovim_user }}/.config/github-copilot"
neovim_github_copilot_dest_key: "{{ neovim_github_copilot_dest_dir }}/apps.json"

# force rebuild of Neovim from source
neovim_force_build: false

neovim_dependencies:
  - "ninja-build"
  - "gettext"
  - "cmake"
  - "g++"
  - "unzip"
  - "curl"

neovim_bundle_dependencies:
  - libuv1-dev
  - libtermkey-dev
  - libvterm-dev
  - luajit
  - liblua5.1-dev
  - lua-lpeg
  - lua-mpack
  - libmsgpack-dev
  - tree-sitter-cli

neovim_plugin_dependencies:
  - "ripgrep"
  - "luarocks"
