---
# defaults file for neovim role

# Define the user for whom Neovim will be installed.
neovim_user: "{{ ansible_user_id }}"
# Define the group for which Neovim will be installed.
neovim_user_group: "{{ neovim_user }}"

# Determines if the installation is shared/system-wide or user-specific.
neovim_shared: false

# Where to install Neovim. By default:
# - /opt/neovim if system-wide (shared)
# - ~/.local/neovim if user-specific
neovim_install_path: >-
  {{ '/opt/neovim' if neovim_shared
     else '~' + neovim_user + '/.local/neovim' }}

# Git repo to clone for building Neovim from source.
neovim_src_repo: "https://github.com/neovim/neovim.git"
# Branch to build from (default: master).
neovim_src_branch: "master"

# Optional config paths. If you have dotfiles or custom config, set these.
neovim_src_config: ""
neovim_dest_config: ""

neovim_enable_github_copilot: true
