#!/usr/bin/env bash

set -e

# First argument is the playbook name
PLAYBOOK=""
if [ -z "$1" ]; then
  PLAYBOOK="install"
else
  PLAYBOOK="install_$1"
fi

if ! command -v ansible >/dev/null 2>&1; then
  echo "Ansible is not installed. Installing..."
  echo "Checking if pipx is installed..."
  if ! command -v pipx >/dev/null 2>&1; then
    echo "pipx is not installed. Installing..."
    python3 -m pip install --user pipx
  else
    echo "pipx is installed."
  fi
  python3 -m pipx install ansible
  python3 -m pipx ensurepath
fi

mkdir -p ~/.ssh
if [ ! -f ~/.dotfiles/ssh/id_rsa ]; then
  ANSIBLE_CONFIG="./ansible.cfg" \
    ansible-playbook \
    "./ansible/playbooks/install_sshkey.yml" \
    --ask-become-pass \
    --ask-vault-pass \
    -e "ansible_user=$(whoami)"
else
  echo "SSH key already exists. Skipping..."
fi

# Run Ansible bootstrap playbook
echo "Running Ansible playbook..."
ANSIBLE_CONFIG="./ansible.cfg" \
  ansible-playbook \
  "./playbooks/${PLAYBOOK}.yml" \
  --ask-become-pass \
  -e "ansible_user=$(whoami)"
