#!/usr/bin/env bash

set -e

# First argument is the playbook name
PLAYBOOK=""
if [ -z "$1" ]; then
  PLAYBOOK="install"
else
  PLAYBOOK="install_$1"
fi

# second argument is vault password file (default .vault.password.txt)
BECOME_FILE="$2"
if [ -z "$2" ]; then
  BECOME_FILE="$HOME/.become.password.txt"
fi

if [ ! -f "$BECOME_FILE" ]; then
  echo "$BECOME_FILE does not exists"
  exit 1
fi

BECOME_PASS=$(cat "$BECOME_FILE")

VAULT_FILE="$3"
if [ -z "$3" ]; then
  VAULT_FILE="$HOME/.vault.password.txt"
fi

if [ ! -f "$VAULT_FILE" ]; then
  echo "$VAULT_FILE does not exists"
  exit 1
fi

# Build extra vars based on environment variables
EXTRA_VARS="dotfiles_user=$(whoami) ansible_become_pass=${BECOME_PASS} dotfiles_repo=psmyth94/.dotfiles dotfiles_version=main dotfiles_dir=${HOME}/.dotfiles"

# Check for force rebuild flags from environment variables
if [ -n "$FORCE_NEOVIM" ] && [ "$FORCE_NEOVIM" = "1" ]; then
  EXTRA_VARS="$EXTRA_VARS install_neovim_force_rebuild=y"
fi

if [ -n "$FORCE_BUILD" ] && [ "$FORCE_BUILD" = "1" ]; then
  EXTRA_VARS="$EXTRA_VARS install_neovim_force_rebuild=y"
fi

# Run Ansible bootstrap playbook
echo "Running Ansible playbook..."
ANSIBLE_CONFIG="./ansible.cfg" \
  ansible-playbook \
  "./playbooks/${PLAYBOOK}.yml" \
  --vault-password-file="$VAULT_FILE" \
  -e "$EXTRA_VARS"
