---
- ansible.builtin.include_tasks: install_linux.yml
  when: ansible_system != "Windows"

- ansible.builtin.include_tasks: install_windows.yml
  when: ansible_system == "Windows"

- ansible.builtin.include_tasks: configure.yml
