---
- ansible.builtin.include_tasks: install_linux.yml
  when: ansible_system != "Windows"
  tags:
    - nodejs
    - install
    - linux

- ansible.builtin.include_tasks: install_windows.yml
  when: ansible_system == "Windows"
  tags:
    - nodejs
    - install
    - windows

- ansible.builtin.include_tasks: configure.yml
  tags:
    - nodejs
    - configure
