---
- name: Update apt cache
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
  when: ansible_pkg_mgr == 'apt'
  changed_when: false
  become: true

- name: Install stow and git
  ansible.builtin.package:
    name:
      - stow
      - git
    state: present
  become: "{{ 'false' if ansible_pkg_mgr == 'homebrew' else 'true' }}"

- name: Build directories list
  ansible.builtin.find:
    paths: ["{{ dotfiles_repo_local_destination }}"]
    recurse: false
    file_type: directory
  register: files

- name: Deploy dotfiles
  with_items: '{{ files.files }}'
  ansible.builtin.command:
    cmd: |
      stow --verbose=2 --target={{ dotfiles_home }} {{ item.path | basename }}
      {% if 'adopt' in dotfiles_conflict_mode %} --adopt{% endif %}
    chdir: "{{ dotfiles_repo_local_destination }}"
  register: result
  changed_when: 'result.stderr is search("LINK: ")'

- name: Revert dotfiles repository after adopt
  ansible.builtin.command:
    cmd: "git restore ."
    chdir: "{{ dotfiles_repo_local_destination }}"
  changed_when: false
  when: dotfiles_conflict_mode == 'adopt_and_reset'
