---
- name: Update apt cache
  ansible.builtin.package:
    update_cache: true
    cache_valid_time: 86400
  become: true
  become_user: "root"
  when: ansible_pkg_mgr == 'apt'
  changed_when: false

- name: Install stow and git
  ansible.builtin.package:
    name:
      - stow
      - git
    state: present
  become: true
  become_user: "{{ 'root' if ansible_pkg_mgr != 'homebrew' else stow_user }}"

- name: Build directories list
  ansible.builtin.find:
    paths: ["{{ stow_dotfiles_dir }}"]
    recurse: false
    file_type: directory
  register: stow_directories

- name: Deploy dotfiles
  with_items: '{{ stow_directories.files }}'
  ansible.builtin.command:
    cmd: |
      stow --verbose=2 --target={{ stow_target_dir }} {{ item.path | basename }}
      {% if 'adopt' in stow_conflict_mode %} --adopt{% endif %}
    chdir: "{{ stow_dotfiles_dir }}"
  register: stow_result
  changed_when: 'stow_result.stderr is search("LINK: ")'

- name: Revert dotfiles repository after adopt
  ansible.builtin.command:
    cmd: "git restore ."
    chdir: "{{ stow_dotfiles_dir }}"
  changed_when: false
  when: stow_conflict_mode == 'adopt_and_reset'
