---
- name: Make zsh default shell
  ansible.builtin.user:
    name: "{{ ansible_user }}"
    shell: /bin/zsh
    update_password: on_create
  when: 
    - zsh_user != 'root'
    - zsh_change_user_shell | default(true)
    - not zsh_install_oh_my_zsh | default(false)

- name: Installing oh-my-zsh
  ansible.builtin.include_role:
	  name: viasite-ansible.zsh
    # add all remaining vars
  



