---
stow_user: "{{ ansible_user_id }}"
stow_home_dir: "/home/{{ stow_user }}"
stow_dotfiles_dir: "{{ stow_home_dir }}/.dotfiles"
stow_target_dir: "{{ stow_home_dir }}"
stow_conflict_mode: "adopt_and_reset"
