---
- name: Reset antigen cache
  command: "timeout 10s /bin/zsh -c 'source {{ oh_my_zsh_config }}; antigen reset'"
  become: yes
  become_user: "{{ oh_my_zsh_user }}"
  changed_when: false
  failed_when: false

# it will fail, but it install all bundles for user
- name: Update antigen bundles
  command: "timeout 30s /bin/zsh -c 'source {{ oh_my_zsh_config }}; antigen update'"
  become: yes
  become_user: "{{ oh_my_zsh_user }}"
  changed_when: false
  failed_when: false

- name: Create cache dirs
  file:
    path: "{{ item }}"
    state: directory
    recurse: yes
    owner: "{{ oh_my_zsh_user }}"
    group: "{{ oh_my_zsh_user_group }}"
  become: yes
  with_items:
    - "{{ oh_my_zsh_antigen_path }}/bundles/robbyrussell/oh-my-zsh/cache/completions"
