---
- name: Detect if running on WSL
  ansible.builtin.command: cat /proc/version
  register: wsl_version
  changed_when: false
  failed_when: false

- name: Set is_wsl fact
  ansible.builtin.set_fact:
    is_wsl: "{{ ('microsoft' in wsl_version.stdout | lower) or ('wsl' in wsl_version.stdout | lower) }}"
  changed_when: false

- name: Check if win32yank is already installed
  ansible.builtin.stat:
    path: /usr/local/bin/win32yank.exe
  register: win32yank_stat
  when: is_wsl

- name: Download and extract win32yank
  ansible.builtin.unarchive:
    src: "https://github.com/equalsraf/win32yank/releases/download/v0.0.4/win32yank-x64.zip"
    dest: "/tmp"
    remote_src: true
    creates: "/tmp/win32yank.exe"
  when: is_wsl and not win32yank_stat.stat.exists

- name: Move win32yank into /usr/local/bin
  ansible.builtin.copy:
    src: /tmp/win32yank.exe
    dest: /usr/local/bin/win32yank.exe
    mode: '0755'
    remote_src: true
  become: true
  become_user: root
  when: is_wsl and not win32yank_stat.stat.exists

- name: Remove temporary win32yank file
  ansible.builtin.file:
    path: /tmp/win32yank.exe
    state: absent
  when: is_wsl and win32yank_stat.stat.exists
