---
- name: Remove existing tmux configuration
  become: true
  become_user: "{{ tmux_user }}"
  ansible.builtin.file:
    path: "{{ item }}"
    state: absent
  with_items: "{{ tmux_paths }}"
  when:
    - item is not none
    - tmux_force_build

- name: Detect if running on WSL
  ansible.builtin.command: cat /proc/version
  register: wsl_version
  changed_when: false
  failed_when: false

- name: Set is_wsl fact
  ansible.builtin.set_fact:
    is_wsl: "{{ ('microsoft' in wsl_version.stdout | lower) or ('wsl' in wsl_version.stdout | lower) }}"
  changed_when: false

- name: Ensure directory for tmux config
  become: true
  become_user: "{{ tmux_user }}"
  ansible.builtin.file:
    path: "{{ tmux_dest_config_dir }}"
    state: directory
    mode: '0755'

- name: Ensure .tmux.conf is linked to oh-my-tmux
  become: true
  become_user: "{{ tmux_user }}"
  ansible.builtin.file:
    src: "{{ tmux_install_dir }}/.tmux.conf"
    dest: "{{ tmux_dest_config }}"
    state: link
    mode: '0755'
    force: true

- name: Ensure .tmux.conf.local is copied or linked
  become: true
  become_user: "{{ tmux_user }}"
  ansible.builtin.copy:
    src: "{{ tmux_src_local_config_wsl if is_wsl else tmux_src_local_config }}"
    dest: "{{ tmux_dest_local_config }}"
    mode: '0755'
    force: true
  when: tmux_src_local_config_wsl != '' or tmux_src_local_config != ''
