---
- include_tasks: install.yml
  tags:
    - tmux
    - install

- include_tasks: post-install.yml
  tags:
    - tmux
    - configure

- include_tasks: source-for-users-shared.yml
  tags:
    - tmux
    - install
  when: tmux_shared and tmux_source_for_all_users
