---
- name: Check if tmux is installed
  ansible.builtin.command: bash -c "command -v tmux"
  register: tmux_check
  changed_when: false

- name: Check if we need to install tmux
  ansible.builtin.set_fact:
    tmux_needs_build: "{{ tmux_check.rc != 0 or tmux_force_build }}"
  changed_when: false

- ansible.builtin.include_tasks: install.yml
  tags:
    - tmux
    - install
  when: tmux_needs_build

- name: Check if oh-my-tmux exists
  ansible.builtin.stat:
    path: "{{ tmux_install_dir }}/.tmux.conf"
  register: oh_my_tmux_check

- name: Clone oh-my-tmux if not exists
  ansible.builtin.command:
    cmd: "gh repo clone {{ tmux_repo }} {{ tmux_install_dir }} -- --branch {{ tmux_repo_version }}"
    creates: "{{ tmux_install_dir }}"
  become: true
  become_user: "{{ tmux_user }}"
  when: not oh_my_tmux_check.stat.exists

- ansible.builtin.include_tasks: configure.yml
  tags:
    - tmux
    - configure

- ansible.builtin.include_tasks: source-for-users-shared.yml
  tags:
    - tmux
    - source
  when: tmux_shared and tmux_source_for_all_users
