---
- name: Remove old Docker versions
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-doc
      - docker-compose
      - docker-compose-v2
      - podman-docker
      - containerd
      - runc
    state: absent
  become: true
  become_user: "root"

- name: Install required packages
  ansible.builtin.apt:
    name:
      - ca-certificates
      - curl
    state: present

- name: Create Docker keyring directory
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'
  become: true
  become_user: "root"

- name: Download Docker's GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
  become: true
  become_user: "root"

- name: Make Docker GPG key readable
  ansible.builtin.file:
    path: /etc/apt/keyrings/docker.asc
    mode: '0644'
  become: true
  become_user: "root"

- name: Get system architecture
  ansible.builtin.command: dpkg --print-architecture
  register: system_architecture
  changed_when: false

- name: Get Ubuntu codename
  ansible.builtin.shell: |
    . /etc/os-release && echo "${UBUNTU_CODENAME:-$VERSION_CODENAME}"
  register: ubuntu_codename
  changed_when: false

- name: Create Docker repository file
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/docker.list
    content: "deb [arch={{ system_architecture.stdout }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ubuntu_codename.stdout }} stable"
    mode: '0644'
  become: true
  become_user: "root"

- name: Update apt cache again
  ansible.builtin.apt:
    update_cache: yes
  become: true
  become_user: "root"

- name: Install Docker engine
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  become: true
  become_user: "root"

- name: Add current user to Docker group
  ansible.builtin.user:
    name: "{{ docker_user }}"
    groups: docker
    append: true
  become: true
  become_user: "root"
