---
- name: Remove old Docker versions
  ansible.builtin.apt:
    name:
      - docker.io
      - docker-doc
      - docker-compose
      - docker-compose-v2
      - podman-docker
      - containerd
      - runc
    state: absent
  become: true
  become_user: "root"

- name: Create directory for Docker GPG key
  ansible.builtin.file:
    path: /etc/apt/keyrings
    state: directory
    mode: "0755"

- name: Get Docker GPG key
  ansible.builtin.get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'
  become: true
  become_user: "root"


- name: Adjust permissions for Docker key
  ansible.builtin.file:
    path: /etc/apt/keyrings/docker.asc
    mode: '0644'
  become: true
  become_user: "root"

- name: Add Docker repository
  ansible.builtin.apt_repository:
    repo: "deb [arch={{ ansible_architecture }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable"
    state: present
  become: true
  become_user: "root"

- name: Update apt cache after Docker repo
  ansible.builtin.apt:
    update_cache: true
  become: true
  become_user: "root"

- name: Install Docker engine
  ansible.builtin.apt:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: present
  become: true
  become_user: "root"

- name: Add current user to Docker group
  ansible.builtin.user:
    name: "{{ docker_user }}"
    groups: docker
    append: true
  become: true
  become_user: "root"
