---
- name: Docker Setup
  hosts: localhost
  become: true
  become_user: "{{ dotfiles_user }}"
  vars:
    dotfiles_repo: "{{ dotfiles_repo | default('') }}"
  tasks:
    - name: Setup docker
      ansible.builtin.include_role:
        name: docker
      vars:
        docker_user: "{{ dotfiles_user }}"
