---
- name: Setup neovim
  hosts: localhost
  become: true
  become_user: "{{ dotfiles_user }}"
  vars_prompt:
    - name: install_neovim_force_rebuild
      prompt: "Do you want to force rebuild Neovim from source? (y/n)"
      private: false
      default: n
    - name: install_neovim_from_source
      prompt: "Do you want to build Neovim from source? (y/n)"
      private: false
      default: n
    - name: install_neovim_branch
      prompt: |
        Which branch do you want to build Neovim from?
      private: false
      default: master
    - name: install_neovim_release
      prompt: |
        Which release do you want to download?
      private: false
      default: stable
    - name: pull_dotfiles
      prompt: "Do you want to pull the latest dotfiles? (y/n)"
      private: false
      default: y

  vars:
    dotfiles_repo: "{{ dotfiles_repo | default('') }}"
    dotfiles_dir: "~{{ dotfiles_user }}/.dotfiles"
    dotfiles_version: "{{ dotfiles_version | default('main') }}"
  tasks:
    - name: Check if dotfiles exists
      ansible.builtin.stat:
        path: "{{ dotfiles_dir }}"
      register: dotfiles_dir_check
      when: pull_dotfiles == 'y' and dotfiles_repo | length > 0

    - name: Clone dotfiles
      ansible.builtin.command:
        cmd: "gh repo clone {{ dotfiles_repo }} {{ dotfiles_dir }} -- --recursive --branch {{ dotfiles_version }}"
      when: pull_dotfiles == 'y' and dotfiles_repo | length > 0 and not dotfiles_dir_check.stat.exists

    - name: Update dotfiles
      ansible.builtin.command:
        cmd: "git -C {{ dotfiles_dir }} pull --recurse-submodules"
      register: dotfiles_pull_result
      changed_when: "'Already up to date' not in dotfiles_pull_result.stdout"
      when: pull_dotfiles == 'y' and dotfiles_repo | length > 0 and dotfiles_dir_check.stat.exists
    - name: Setup neovim
      ansible.builtin.include_role:
        name: neovim
      vars:
        neovim_user: "{{ dotfiles_user }}"
        neovim_force_build: "{{ install_neovim_force_rebuild == 'y' }}"
        neovim_dotfiles_dir: "{{ dotfiles_dir }}"
        neovim_from_source: "{{ install_neovim_from_source == 'y' }}"
        neovim_branch: "{{ install_neovim_branch }}"
        neovim_release: "{{ install_neovim_release }}"
      tags:
        - install
        - configure
        - github-copilot
