---
- name: Setup nodejs
  hosts: localhost
  become: true
  become_user: "{{ dotfiles_user }}"

  vars_prompt:
    - name: force_build
      prompt: "Reinstall if already installed? (y/n)"
      private: false
      default: n
  roles:
    - role: nodejs
      vars:
        nodejs_user: "{{ dotfiles_user }}"
        nodejs_force_build: "{{ force_build == 'y' }}"
