---
- name: Setup neovim
  hosts: localhost
  become: true
  become_user: "{{ dotfiles_user }}"
  vars_prompt:
    - name: neovim_force_rebuild
      prompt: "Do you want to force rebuild Neovim from source? (y/[n])"
      private: false
      default: n

  vars:
    dotfiles_repo: "{{ dotfiles_repo | default('') }}"
    dotfiles_dir: "~{{ dotfiles_user }}/.dotfiles"
    dotfiles_version: "{{ dotfiles_version | default('main') }}"
  tasks:
    - name: Setup Dotfiles
      ansible.builtin.git:
        repo: "{{ dotfiles_repo }}"
        dest: "{{ dotfiles_dir }}"
        version: "{{ dotfiles_version }}"
        update: true
        recursive: true
        track_submodules: true
        force: true
    - name: Setup neovim
      ansible.builtin.include_role:
        name: neovim
      vars:
        neovim_user: "{{ dotfiles_user }}"
        neovim_force_build: "{{ neovim_force_rebuild == 'y' }}"
        neovim_dotfiles_dir: "{{ dotfiles_dir }}"
      tags:
        - install
        - configure
        - github-copilot
