---
- name: Setup tmux
  hosts: localhost
  become: true
  become_user: "{{ dotfiles_user }}"

  vars_prompt:
    - name: dotfiles_force_build
      prompt: "Remove previous tmux installation and build from source?"
      private: false
      default: "n"
  vars:
    dotfiles_repo: "{{ dotfiles_repo | default('') }}"
    dotfiles_dir: "~{{ dotfiles_user }}/.dotfiles"
    dotfiles_version: "{{ dotfiles_version | default('main') }}"
  tasks:
    - name: Check if dotfiles exists
      ansible.builtin.stat:
        path: "{{ dotfiles_dir }}"
      register: dotfiles_dir_check
      when: dotfiles_repo | length > 0

    - name: Clone dotfiles
      ansible.builtin.command:
        cmd: "gh repo clone {{ dotfiles_repo }} {{ dotfiles_dir }} -- --recursive --branch {{ dotfiles_version }}"
      when: dotfiles_repo | length > 0 and not dotfiles_dir_check.stat.exists

    - name: Update dotfiles
      ansible.builtin.command:
        cmd: "git -C {{ dotfiles_dir }} pull --recurse-submodules"
      register: dotfiles_pull_result
      changed_when: "'Already up to date' not in dotfiles_pull_result.stdout"
      when: dotfiles_repo | length > 0 and dotfiles_dir_check.stat.exists
    - name: Setup Tmux
      ansible.builtin.include_role:
        name: tmux
      vars:
        tmux_user: "{{ dotfiles_user }}"
        tmux_force_build: "{{ dotfiles_force_build }}"
