---
sshkey_user: "{{ dotfiles_user_id }}"
sshkey_dotfiles_dir: "~{{ sshkey_user }}/.dotfiles"
sshkey_key_type: "id_rsa"
sshkey_source_key: "{{ sshkey_dotfiles_dir }}/ssh/{{ sshkey_key_type }}"
sshkey_dir: "~{{ sshkey_user }}/.ssh"
sshkey_dest_key: "{{ sshkey_dir }}/{{ sshkey_key_type }}"
