---
sshkey_user: "{{ dotfiles_user_id }}"
sshkey_dotfiles_dir: "~{{ sshkey_user }}/.dotfiles"
sshkey_key_type: "id_ed25519"
sshkey_source_priv_key: "{{ sshkey_dotfiles_dir }}/ssh/{{ sshkey_key_type }}"
sshkey_source_pub_key: "{{ sshkey_dotfiles_dir }}/ssh/{{ sshkey_key_type }}.pub"
sshkey_dir: "~{{ sshkey_user }}/.ssh"
sshkey_dest_priv_key: "{{ sshkey_dir }}/{{ sshkey_key_type }}"
sshkey_dest_pub_key: "{{ sshkey_dir }}/{{ sshkey_key_type }}.pub"
