---
# remove if exists the destination config directory
- name: Remove the destination config directory if it exists
  ansible.builtin.file:
    path: "{{ neovim_dest_config_dir }}"
    state: absent
  when: neovim_dest_config_dir != ''

# symlink the source config directory to the destination config directory
- name: Symlink the source config directory to the destination config directory
  ansible.builtin.file:
    src: "{{ neovim_src_config_dir }}"
    dest: "{{ neovim_dest_config_dir }}"
    state: link
  when: neovim_src_config_dir != '' and neovim_dest_config_dir != ''

- name: Get XDG_RUNTIME_DIR
  ansible.builtin.set_fact:
    xdg_runtime_dir: "{{ lookup('env', 'XDG_RUNTIME_DIR') }}"
  failed_when: false

- name: Fix for plenary.nvim/issues/536
  become: true
  become_user: "root"
  ansible.builtin.file:
    path: "{{ xdg_runtime_dir }}"
    owner: "{{ neovim_user }}"
    group: "{{ neovim_user_group }}"
    state: directory
    mode: '0700'
  when: xdg_runtime_dir is defined
