---
- name: Ensure github-copilot directory exists
  become: true
  ansible.builtin.file:
    dest: "{{ neovim_github_copilot_dest_dir }}"
    mode: '0700'
    state: directory
    group: "{{ neovim_user_group }}"
    owner: "{{ neovim_user }}"
  tags:
    - github-copilot

- name: Install github-copilot OAuth
  become: true
  ansible.builtin.copy:
    src: "{{ neovim_github_copilot_src_key }}"
    dest: "{{ neovim_github_copilot_dest_key }}"
    mode: '0600'
    group: "{{ neovim_user_group }}"
    owner: "{{ neovim_user }}"
  tags:
    - github-copilot
