---
- name: "Install Neovim"
  ansible.builtin.include_tasks: install.yml
  tags:
    - install

- name: "Configure Neovim"
  ansible.builtin.include_tasks: configure.yml
  tags:
    - configure

- name: "Setup github-copilot plugin"
  ansible.builtin.include_tasks: github-copilot.yml
  when: neovim_enable_github_copilot
  tags:
    - github-copilot

- name: "Setup system-wide for shared installation"
  ansible.builtin.include_tasks: source-for-users-shared.yml
  when: neovim_shared
  tags:
    - shared
