---
- name: Check if Neovim is installed
  become: true
  become_user: "{{ neovim_user }}"
  ansible.builtin.command: bash -c "command -v nvim"
  register: neovim_check
  changed_when: false
  failed_when: false

- name: Determine if Neovim needs to be built
  ansible.builtin.set_fact:
    neovim_needs_build: "{{ neovim_check.rc != 0 or neovim_force_build }}"

- name: "Install Neovim"
  ansible.builtin.include_tasks: install.yml
  tags:
    - install
  when: neovim_needs_build

- name: "Configure Neovim"
  ansible.builtin.include_tasks: configure.yml
  tags:
    - configure

- name: "Setup github-copilot plugin"
  ansible.builtin.include_tasks: github-copilot.yml
  when: neovim_enable_github_copilot
  tags:
    - github-copilot

- name: "Setup system-wide for shared installation"
  ansible.builtin.include_tasks: source-for-users-shared.yml
  when: neovim_shared
  tags:
    - shared
